# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", "200000");
user_pref("browser.cache.memory.capacity", 65535);
user_pref("browser.cache.offline.enable", false);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.download.folderList", 2);
user_pref("browser.download.manager.closeWhenDone", true);
user_pref("browser.download.manager.showAlertOnComplete", false);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.link.open_newwindow.restriction", 0);
user_pref("browser.link.open_newwindow.restriction.backup", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.defaultenginename", "Google");
user_pref("browser.search.defaulturl", "http://www.google.com/search?q=");
user_pref("browser.showQuitWarning", true);
user_pref("browser.startup.page", 3);
user_pref("browser.tabs.animate", false);
user_pref("browser.tabs.closeWindowWithLastTab", false);
user_pref("browser.tabs.insertRelatedAfterCurrent", false);
user_pref("browser.tabs.loadFolderAndReplace", false);
user_pref("browser.tabs.onTop", false);

user_pref("dom.disable_window_move_resize", true);
user_pref("dom.event.contextmenu.enabled", false);
user_pref("dom.max_script_run_time", 20);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 13);
user_pref("extensions.greasemonkey.haveInsertedToolbarbutton", true);
user_pref("extensions.greasemonkey.stats.optedin", true);
user_pref("extensions.greasemonkey.stats.prompted", true);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.testpilot.alreadyCustomizedToolbar", true);

user_pref("extensions.treestyletab.animation.enabled", false);
user_pref("extensions.treestyletab.autoCollapseExpandSubtreeOnSelect", false);
user_pref("extensions.treestyletab.bookmarkDroppedTabs.behavior", 1);
user_pref("extensions.treestyletab.orientalPrefsMigrated", 2);
user_pref("extensions.treestyletab.preferences.newTab-tabbox.selectedIndex", 4);
user_pref("extensions.treestyletab.prefsVersion", 9);
user_pref("extensions.treestyletab.show.context-item-bookmarkTabSubtree", false);
user_pref("extensions.treestyletab.show.context-item-collapseAllSubtree", false);
user_pref("extensions.treestyletab.show.context-item-expandAllSubtree", false);
user_pref("extensions.treestyletab.show.context-item-reloadTabSubtree", false);
user_pref("extensions.treestyletab.show.context-item-removeTabSubtree", false);
user_pref("extensions.treestyletab.show.context-item-toggleAutoHide", false);
user_pref("extensions.treestyletab.show.context-item-toggleFixed", false);
user_pref("extensions.treestyletab.show.context-menu-tabbarPosition", false);
user_pref("extensions.treestyletab.show.openSelectionLinks", false);
user_pref("extensions.treestyletab.tabbar.height", 29);
user_pref("extensions.treestyletab.tabbar.hideNewTabButton.horizontal", true);
user_pref("extensions.treestyletab.tabbar.hideNewTabButton.vertical", true);
user_pref("extensions.treestyletab.tabbar.shrunkenWidth", 0);
user_pref("extensions.treestyletab.tabbar.transparent.style", 0);
user_pref("extensions.treestyletab.tabbar.width", 130);
user_pref("extensions.treestyletab.tabsOnTop.originalState", false);
user_pref("extensions.treestyletab.twisty.style", "modern-black");
user_pref("extensions.treestyletab.undoCloseTabSet.behavior", 0);
user_pref("extensions.treestyletab.urlbar.loadDifferentDomainToNewTab", false);
user_pref("extensions.treestyletab.urlbar.loadSameDomainToNewTab", false);
user_pref("extensions.treestyletab.urlbar.loadSameDomainToNewTab.asChild", false);

user_pref("extensions.update.notifyUser", false);

user_pref("extensions.xnotifier.customSound", true);
user_pref("extensions.xnotifier.menuSidebar", false);
user_pref("extensions.xnotifier.menuWindow", false);
user_pref("extensions.xnotifier.showTabMenu", false);
user_pref("extensions.xnotifier.soundUrl", "file:///usr/share/sounds/purple/login.wav");
user_pref("extensions.xnotifier.updateInterval", 5);

user_pref("fireftp.donated", true);
user_pref("font.minimum-size.x-western", 9);
user_pref("font.size.variable.x-western", 14);
user_pref("general.warnOnAboutConfig", false);

user_pref("imagezoom.globalZoomWarning", true);
user_pref("imagezoom.scrollvalue", 7);
user_pref("imagezoom.showAutoFitInMenu", true);
user_pref("imagezoom.showViewMenu", false);
user_pref("imagezoom.smCustomDim", false);
user_pref("imagezoom.smCustomZoom", false);
user_pref("imagezoom.smFitWindow", false);
user_pref("imagezoom.smZoomPcts", false);

user_pref("inspector.dom.showAccessibleNodes", true);

user_pref("intl.accept_languages", "en,sl");
user_pref("intl.charset.default", "UTF-8");
user_pref("intl.charset.detector", "universal_charset_detector");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");

user_pref("javascript.options.jit.chrome", true);

user_pref("keyconfig.global.20110522", "");
user_pref("keyconfig.main.addBookmarkAsKb", "!][][");
user_pref("keyconfig.main.gtbSearchKey", "control][K][");
user_pref("keyconfig.main.key_closeWindow", "!][][");
user_pref("keyconfig.main.key_gotoHistory", "!][][");
user_pref("keyconfig.main.key_quitApplication", "!][][");
user_pref("keyconfig.main.key_sanitize", "!][][");
user_pref("keyconfig.main.key_savePage", "!][][");
user_pref("keyconfig.main.key_search", "control][J][");
user_pref("keyconfig.main.key_search2", "!][][");
user_pref("keyconfig.main.manBookmarkKb", "!][][");
user_pref("keyconfig.main.showAllHistoryKb", "!][][");
user_pref("keyconfig.main.viewBookmarksSidebarKb", "!][][");
user_pref("keyconfig.main.web-developer-view-response-headers-key", "control shift][H][");
user_pref("keyconfig.main.webdeveloper-disable-styles-key", "!][][");

user_pref("keyword.URL", "http://www.google.com/search?q=");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.no_proxies_on", "localhost, 127.0.0.1, google.com, gmail.com");

user_pref("noscript.ABE.migration", 1);
user_pref("noscript.allowURLBarJS", true);
user_pref("noscript.autoAllow", 3);
user_pref("noscript.autoReload", false);
user_pref("noscript.autoReload.allTabs", false);
user_pref("noscript.confirmUnsafeReload", false);
user_pref("noscript.ctxMenu", false);
user_pref("noscript.gtemp", "");
user_pref("noscript.notify", false);
user_pref("noscript.notify.hide", true);
user_pref("noscript.policynames", "");
user_pref("noscript.visibleUIChecked", true);

user_pref("pref.privacy.disable_button.view_passwords", false);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.warn_viewing_mixed", false);

user_pref("textlink.actions.0.action", 32);
user_pref("textlink.actions.1.action", 0);
user_pref("textlink.actions.1.trigger.key", "");
user_pref("textlink.actions.1.trigger.mouse", "");
user_pref("textlink.actions.2.action", 0);
user_pref("textlink.actions.2.trigger.key", "");
user_pref("textlink.actions.2.trigger.mouse", "");
user_pref("textlink.prefsVersion", 1);
user_pref("textlink.scheme", "http https ftp news nntp telnet irc mms ed2k about file urn hxxp");
user_pref("textlink.scheme.fixup.table", "www=>http://www ftp.=>ftp://ftp. irc.=>irc:irc. h??p=>http h???s=>https ttp=>http tp=>http p=>http ttps=>https tps=>https ps=>https hxxp=>http");

user_pref("view_source.wrap_long_lines", true);
